#!/bin/sh
# Builds every Proxy Mono font in one command: fonts/variable, fonts/ttf and fonts/webfonts.
# The fonts are generated by sources/generator/az.py from the upstream fonts in sources/upstream.
set -e
cd "$(dirname "$0")/.."
make build
